# GitHub Action workflow file

name: iOS Build

on:
  push:
    branches:
      - develop
      - main
      - sprint*
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  swiftLint:
    uses: ./.github/workflows/swiftlint.yml
# YAML file without @version due to using the local repository file

  build:
#    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/fastlane-build-only.yml
#    secrets: inherit
