name: iOS Build

on:
  push:
    branches:
      - develop
      - main
      - sprint*
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  lint:
    steps:
    - name: check-warnings
      if: github.event_name != 'pull_request'
      uses: ./.github/workflows/swiftlint.yml
# YAML file without @version due to using the local repository file

    - name: check-strict
      if: github.event_name == 'pull_request'
      uses: ./.github/workflows/swiftlint-strict.yml

  build:
    uses: ./.github/workflows/fastlane-build-only.yml
#    secrets: inherit
