# GitHub Action workflow file

name: SwiftLint (with warnings)

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  check-with-warnings:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        if: github.event_name != 'pull_request'
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --no-cahce
#          args: --no-cahce --config swiftlint.yml
 
  check-strict:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        if: github.event_name == 'pull_request'
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict --no-cahce --config swiftlint.yml
 
  try-build:
    uses: ./.github/workflows/fastlane-build-only.yml
# YAML file without @version due to using the local repository file

#        with:
#          args: --config swiftlint.yml
#
#      - name: GitHub Action for SwiftLint with --strict
#        uses: norio-nomura/action-swiftlint@3.2.1
#        with:
#          args: --strict
#
#      - name: GitHub Action for SwiftLint (Only files changed in the PR)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          DIFF_BASE: ${{ github.base_ref }}
#
#      - name: GitHub Action for SwiftLint (Different working directory)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          WORKING_DIRECTORY: Source
