# GitHub Action workflow file

name: SwiftLint

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  check-with-warnings:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint --no-cache --config swiftlintt.yml
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
#          args: --no-cache
          args: --no-cache --config swiftlintt.yml
 
  check-strict:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint --strict --no-cache --config swiftlint.yml
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict --no-cache --config swiftlint.yml
 
#      - name: GitHub Action for SwiftLint (Only files changed in the PR)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          DIFF_BASE: ${{ github.base_ref }}
#
#      - name: GitHub Action for SwiftLint (Different working directory)
#        uses: norio-nomura/action-swiftlint@3.2.1
#        env:
#          WORKING_DIRECTORY: Source
